### ISSUE TITLE
Popup position and Latte dock right click

### ISSUE THREAD

**Issue by ghost** [nx-desktop/nx-systemtray-applet#2]
1. Why popup window isn't alignment to right ?

![screenshot_20170824_192603](https://user-images.githubusercontent.com/15931906/29679617-646ad9f6-8902-11e7-8f5f-461cab5fd19b.png)

2. I'm using Manjaro + git version of Latte dock. Top bar is Latte too. There's no entire menu when i right click any of nomad system tray items. With normal system tray it is working. With normal panel + nomad tray its working too.  

![screenshot_20170824_192636](https://user-images.githubusercontent.com/15931906/29679620-66a49626-8902-11e7-8a98-88e62d071f0b.png)

**Comment by azubieta** [comment]
1. Popup alignment is to the nearest screen border, if it's in the right so the popup will be aligned to the right but only if there isn't a big distance from that border. Otherwise the user (you) will have to move your mouse cursor too much from where you made the first click.

2. Sorry, what do you mean by "entire menu"?

**Comment by ghost** [comment]
2. For example Audio Controls when right click have "Audio Controls Settings" 
(First screen - standard tray ,second - nomad tray
![screenshot_20170824_224041](https://user-images.githubusercontent.com/15931906/29687618-562fd4e8-891d-11e7-8687-8a8726d9104a.png)
![screenshot_20170824_224055](https://user-images.githubusercontent.com/15931906/29687622-57c66db2-891d-11e7-940a-f9335b1bd711.png)
